<x-home
    :products="$products"
    :featuredProduct="$featuredProduct ?? null"
    :promotionProducts="$promotionProducts ?? collect()"
    :topSellingProducts="$topSellingProducts ?? collect()"
    :brandList="$brandList ?? []"
    :categories="$categories ?? []"
    :category-tree="$categoryTree ?? []"
    :brands="$brands ?? []"
    :selectedCategories="$selectedCategories ?? []"
    :selectedSubCategories="$selectedSubCategories ?? []"
    :selectedBrands="$selectedBrands ?? []"
    :search="$search ?? ''"
    :subCategoriesByCategory="$subCategoriesByCategory ?? []"
/>
